name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  x64:
    name: x64 ${{ matrix.configuration }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Configure
        run: >-
          cmake -S . -B build/x64
          -G "Visual Studio 17 2022" -A x64
          -DMWTL_BUILD_EXAMPLES=ON
          -DMWTL_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build/x64 --config ${{ matrix.configuration }} --verbose

      - name: Test
        run: ctest --test-dir build/x64 -C ${{ matrix.configuration }} --output-on-failure
